# Rake file for running sinatra apps and committing code to maglev.
# Default is to commit code (if necessary) and run both apps

task :default => :objectlog

desc "Commit the base blog code to the repository."
task :commit, :force do |t,args|
  sh %{ maglev-ruby -MnoRlwrap commit_code.rb #{args.force} }
end

desc "Run the objectlog app standalone."
task :objectlog  do
  sh %{ $MAGLEV_HOME/bin/rackup objectlog.ru }
end
