# Rake file for running sinatra apps and committing code to maglev.
# Default is to commit code (if necessary) and run both apps

task :default => :objectlog

desc "Run the objectlog app standalone."
task :objectlog  do
  sh %{ $MAGLEV_HOME/bin/rackup objectlog.ru }
end
