module G
  class << self
    def define_module_function(name, &block)
      define_method(name, &block)
      module_function(name)
    end
  end
  define_module_function :system, &Kernel.method(:system)
end


#################### Trac Info
# ID:         494
# Summary:    rake gem hits "No method was found for the selector #'_copyForRuby:'"
# Changetime: 2009-04-29 16:42:31+00:00
###

#  rake gem installs OK, but doesn't run.
#  
#  {{{
#  $ maglev-gem install rake
#  $ head bin/rake
#  #!/usr/bin/env maglev-ruby
#  #
#  # This file was generated by RubyGems.
#  #
#  # The application 'rake' is installed as part of a gem, and
#  # this file is here to facilitate running it.
#  $ maglev-ruby bin/rake -T
#  ERROR 2010, No method was found for the selector #'_copyForRuby:' when sent to aRubyMeth with arguments contained in anArray( 1).
#  }}}
#  