task :default => :query

desc "Run the social web app"
task :run do
  sh "$MAGLEV_HOME/bin/rackup -I lib config.ru"
end

desc "Build the database of people and connections; commit code and data"
task :build, :force do |t,args|
  sh "maglev-ruby build_graph.rb #{args.force}"
end

desc "Run a query on the database; only rebuilds db if non-existant."
task :query do
  sh "maglev-ruby query.rb"
end

# namespace :sinatra do
#   desc "Commit sinatra code to the repository"
#   task :commit do
#     commands = <<-'EOS'
#        Maglev.persistent do
#          require "rubygems"
#          require "sinatra"
#        end
#        Maglev.commit_transaction
#     EOS
#   end
# end
