task :default => :run

MH = ENV['MAGLEV_HOME']

desc "Run the WebTools Sinatra App"
task :run do
  sh "#{MH}/bin/rackup -Ilib config.ru"
end

desc "Run a simple web app to view code and statistics."
task :webtools, :meta do |t, args|
  # Load the Smalltalk example code into the MagLev repository, and commit it.
  file = "#{MH}/gemstone/examples/www/install.tpz"
  raise "Can't find #{file}" unless File.exists? file
  cd(MH) { sh "rake maglev:input_file[#{file}]" }

  # Enable the MagLev WebTools code
  file = "#{MH}/gemstone/examples/www/src/maglev.rb"
  raise "Can't find #{file}" unless File.exists? file
  sh "maglev-ruby -Mcommit #{file}"

  # Start the server
  sh "maglev-ruby -d web_tools.rb #{args.meta}"
end
