* Notes
** Features to implement
   + Should we add an ontology?  Give meaning to the tags (rdf)?
   + Update model to use ActiveModel validation checks
     (validate_presence_of :password, :username) etc.
   + Add
*** TODO Add date to tweets
*** TODO Add tweet form to home page (allow posting tweets)
*** TODO Allow anyone to look at a user's tweets (user's home)
*** TODO Implement mentions queue for each user
*** TODO Add real persistence
*** TODO Add tagging features
*** TODO Create ORM version

** ActiveRecord

   Many of the efficiencies that the MySQL paper lists, won't be available
   for ActiveRecord, since ActiveRecord uses surrogate keys (id column)
   rather than, e.g.,:

      CREATE TABLE Tag2Post (
        tag_id ...
        post_id ...
        , PRIMARY KEY pk_Tag2Post (tag_id, post_id)
        , INDEX (post_id)
      ) ENGINE=InnoDB;
** Tests and results
   + Tests are run in production mode.  To do this
     1. pass "--env production" to rackup (prevents rack from adding
        extraneous middleware, like lint etc.)
     2. "set :environment, :production" in config.ru tells sinatra to only
        install necessary middleware.
     In general, we'll be running with: content_length and cookie
     middleware.
   + No debug output to tty
   + All test runs start off with a "GET /info" so we can document the ruby
     environment, date and the installed middleware.  Then we run the
     test.
   + TODO: Can we show the sinatra options?
   + TODO: Can we rely on front-end httpd logging instead of common logger?
*** Test 2: Measure the overhead of a transaction per request
    This test was only done on Maglev, as it is the only one with built-in
    transactions.  The setup is similar to Test 1, but we are comparing no
    middleware to one that does a <tt>Maglev.abort_transaction</tt> at the
    beginning of each HTTP request, and does a
    <tt>Maglev.commit_transaction</tt> at the end of each successful HTTP
    request.  This is done via rack middleware:

      class TransactionWrapper
        def initialize(app)
          @app = app
        end

        def call(env)
          begin
            Maglev.abort_transaction
            r = @app.call env
          ensure
            Maglev.commit_transaction if committable? r[0]
          end
        end

        def committable?(status)
          ! status.nil? &&  (200..399).include?(status)
        end
      end

      | Without transactions | 547.64 | 18.260 |
      | With transactions    | 494.56 | 20.220 |
      | Difference           |  53.08 |  -1.96 |

      Looks like transaction overhead (with no data to commit!) take about
      2ms, or about 11% penalty over no transactions.

**** Results w/o transaction wrapper
curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  maglev
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 16:15:36 -0700 2010

========== Middleware ================
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   18.260 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    547.64 [#/sec] (mean)
Time per request:       18.260 [ms] (mean)
Time per request:       1.826 [ms] (mean, across all concurrent requests)
Transfer rate:          152.42 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       5
Processing:     7   18   4.2     18     141
Waiting:        6   18   4.2     17     141
Total:          7   18   4.2     18     141

Percentage of the requests served within a certain time (ms)
  50%     18
  66%     18
  75%     19
  80%     19
  90%     20
  95%     21
  98%     23
  99%     24
 100%    141 (longest request)

**** Results with transaction wrapper
curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  maglev
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 16:12:40 -0700 2010

========== Middleware ================
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/ruby/site_ruby/1.8/maglev/rack_txn_wrapper.rb:34:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/ruby/site_ruby/1.8/maglev/rack_txn_wrapper.rb:35:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   20.220 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    494.56 [#/sec] (mean)
Time per request:       20.220 [ms] (mean)
Time per request:       2.022 [ms] (mean, across all concurrent requests)
Transfer rate:          137.65 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0      11
Processing:     5   20   4.6     19     143
Waiting:        5   20   4.6     19     142
Total:          6   20   4.7     19     143

Percentage of the requests served within a certain time (ms)
  50%     19
  66%     20
  75%     21
  80%     21
  90%     22
  95%     23
  98%     26
  99%     30
 100%    143 (longest request)

*** Test 1: Measure overhead of a rack middleware
    Install an empty Rack middleware app that does nothing.  The intent is
    to distinguish the overhead of the transaction processing vs the rack
    overhead when using the transaction wrapper middleware.

    + The file we loaded was the following 22 characters: /* Empty MagTag.css */

**** Results

     Basically, the overhead of the following rack app is "negligible"
     (less than a quarter of a millisecond, or around 0.5% of an average
     request).

       class EmptyMiddleware
         def initialize(app)
           @app = app
         end

         def call(env)
           @app.call env
         end
       end

     |-------------+-----------+---------+---------+-----------|
     | Middleware  | Ruby      | HTTPd   | req/sec |  mean req |
     |             |           |         |  (mean) | time (ms) |
     |-------------+-----------+---------+---------+-----------|
     | No mid-ware | Maglev    | WEBrick |  543.91 |    18.385 |
     | Empty       | Maglev    | WEBrick |  547.06 |    18.280 |
     |-------------+-----------+---------+---------+-----------|
     | Diff        |           |         |         |           |
     |-------------+-----------+---------+---------+-----------|
     |-------------+-----------+---------+---------+-----------|
     | No mid-ware | MRI 1.8.7 | WEBrick |  399.99 |    25.001 |
     | Empty       | MRI 1.8.7 | WEBrick |  396.57 |    25.216 |
     |-------------+-----------+---------+---------+-----------|
     | Diff        |           |         |         |           |
     |-------------+-----------+---------+---------+-----------|
     |-------------+-----------+---------+---------+-----------|
     | No mid-ware | MRI 1.9.2 | WEBrick |  388.17 |    25.762 |
     | Empty       | MRI 1.9.2 | WEBrick |  389.38 |    25.682 |
     |-------------+-----------+---------+---------+-----------|
     | Diff        |           |         |         |           |

     The MagLev run with the middleware was actually faster than without
     the middleware (by about 2.5%, or so).  Let's assume that is in the
     noise.  It is .8ms faster with the middleware

     1.9.2 is slower!!?? than 1.8.7 ?

**** Maglev Results
***** No middleware

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  maglev
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 15:52:57 -0700 2010

========== Middleware ================
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   18.385 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    543.91 [#/sec] (mean)
Time per request:       18.385 [ms] (mean)
Time per request:       1.839 [ms] (mean, across all concurrent requests)
Transfer rate:          151.38 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.3      0      22
Processing:     6   18   4.6     18     142
Waiting:        6   18   4.6     17     142
Total:          9   18   4.6     18     142

Percentage of the requests served within a certain time (ms)
  50%     18
  66%     18
  75%     19
  80%     19
  90%     20
  95%     21
  98%     23
  99%     27
 100%    142 (longest request)

***** Empty middleware:

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  maglev
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 15:50:51 -0700 2010

========== Middleware ================
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/GemStone/checkouts/git/examples/webstack/lib/empty_middleware.rb:9:in `call'
/Users/pmclain/GemStone/snapshots/current/lib/maglev/gems/1.8/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   18.280 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    547.06 [#/sec] (mean)
Time per request:       18.280 [ms] (mean)
Time per request:       1.828 [ms] (mean, across all concurrent requests)
Transfer rate:          152.26 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.2      0       8
Processing:     4   18   4.6     17     141
Waiting:        4   18   4.6     17     141
Total:          4   18   4.6     18     141

Percentage of the requests served within a certain time (ms)
  50%     18
  66%     18
  75%     19
  80%     19
  90%     20
  95%     21
  98%     23
  99%     26
 100%    141 (longest request)

**** MRI 1.8.7 Results
***** No middleware

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  MRI
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 15:40:41 -0700 2010

========== Middleware ================
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   25.001 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    399.99 [#/sec] (mean)
Time per request:       25.001 [ms] (mean)
Time per request:       2.500 [ms] (mean, across all concurrent requests)
Transfer rate:          111.32 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1  35.1      0     998
Processing:     8   24  10.8     20      62
Waiting:        7   22  10.4     19      62
Total:          8   25  36.6     21    1018

Percentage of the requests served within a certain time (ms)
  50%     21
  66%     21
  75%     22
  80%     22
  90%     50
  95%     53
  98%     55
  99%     56
 100%   1018 (longest request)
***** Empty middleware:
=============================================================

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  MRI
Ruby         1.8.7
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         Tue Oct 05 15:23:03 -0700 2010

========== Middleware ================
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/sinatra-1.0/lib/sinatra/base.rb:863:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
./lib/empty_middleware.rb:9:in `call'
/Users/pmclain/.rvm/gems/ruby-1.8.7-p302/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   25.216 seconds
Complete requests:      10000
Failed requests:        0
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    396.57 [#/sec] (mean)
Time per request:       25.216 [ms] (mean)
Time per request:       2.522 [ms] (mean, across all concurrent requests)
Transfer rate:          110.37 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1  23.5      0     977
Processing:     7   24  10.9     21      61
Waiting:        6   22  10.5     19      59
Total:          8   25  25.8     21     998

Percentage of the requests served within a certain time (ms)
  50%     21
  66%     22
  75%     22
  80%     22
  90%     53
  95%     54
  98%     55
  99%     56
 100%    998 (longest request)

**** MRI 1.9.2 Results
***** No middleware

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  ruby
Ruby         1.9.2
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         2010-10-05 15:43:38 -0700

========== Middleware ================
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.0/lib/sinatra/base.rb:865:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   25.762 seconds
Complete requests:      10000
Failed requests:        1
   (Connect: 1, Receive: 0, Length: 0, Exceptions: 0)
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    388.17 [#/sec] (mean)
Time per request:       25.762 [ms] (mean)
Time per request:       2.576 [ms] (mean, across all concurrent requests)
Transfer rate:          108.04 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    2  39.4      0    1000
Processing:     5   24   5.9     23     142
Waiting:        0   21   5.6     20     139
Total:          9   26  39.8     23    1029

Percentage of the requests served within a certain time (ms)
  50%     23
  66%     26
  75%     30
  80%     30
  90%     31
  95%     32
  98%     33
  99%     36
 100%   1029 (longest request)

***** Empty middleware:

curl http://localhost:3333/info
===== get /info ======================
RUBY_ENGINE  ruby
Ruby         1.9.2
Sinatra      1.0
Rack         1.2
MagTag       0.0.2
Date         2010-10-05 15:46:32 -0700

========== Middleware ================
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.0/lib/sinatra/base.rb:865:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/sinatra-1.0/lib/sinatra/base.rb:399:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/session/cookie.rb:37:in `call'
/Users/pmclain/GemStone/checkouts/git/examples/webstack/lib/empty_middleware.rb:9:in `call'
/Users/pmclain/.rvm/gems/ruby-1.9.2-p0/gems/rack-1.2.1/lib/rack/content_length.rb:13:in `call'
======================================
ab -n 10000 -c 10 http://127.0.0.1:3333/magtag.css
This is ApacheBench, Version 2.3 <$Revision: 655654 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:        WEBrick/1.3.1
Server Hostname:        127.0.0.1
Server Port:            3333

Document Path:          /magtag.css
Document Length:        22 bytes

Concurrency Level:      10
Time taken for tests:   25.682 seconds
Complete requests:      10000
Failed requests:        2
   (Connect: 2, Receive: 0, Length: 0, Exceptions: 0)
Write errors:           0
Total transferred:      2850000 bytes
HTML transferred:       220000 bytes
Requests per second:    389.38 [#/sec] (mean)
Time per request:       25.682 [ms] (mean)
Time per request:       2.568 [ms] (mean, across all concurrent requests)
Transfer rate:          108.37 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    1  31.6      0    1007
Processing:     8   25   5.0     23      57
Waiting:        6   22   4.8     20      52
Total:          8   26  31.9     23    1030

Percentage of the requests served within a certain time (ms)
  50%     23
  66%     28
  75%     30
  80%     30
  90%     31
  95%     32
  98%     34
  99%     36
 100%   1030 (longest request)
