require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "lib"
  t.test_files = FileList['test/test_*.rb']
#  t.test_files = FileList['test/test_user.rb']
  t.ruby_opts << '-rubygems'
  # t.verbose = true
end
