require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "lib"
  t.test_files = FileList['test/test_*.rb']
#  t.test_files = FileList['test/test_user.rb']
  t.ruby_opts << '-rubygems'
  # t.verbose = true
end

desc "Run the MagTag Web App"
task :magtag do
  sh "$MAGLEV_HOME/bin/rackup config.ru"
end
