# task :default => :maglev
task :default => [:rspec, :examples, :cucumber]

desc "run the test case with maglev (default)"
task :rspec do
  sh %{ $MAGLEV_HOME/bin/spec bowling_spec.rb }
end

desc "Run MagLev against the RSpec examples"
task :examples do
  rspec_dir = "#{ENV['MAGLEV_HOME']}/lib/maglev/gems/1.8.7/gems/rspec-1.3.0"
  cd rspec_dir do
    passing = FileList['examples/passing/*_spec.rb']
    failing = FileList['examples/failing/*_spec.rb']

    passing.each { |spec| sh %{ $MAGLEV_HOME/bin/spec #{spec} } }
#    failing.each { |spec| sh %{ $MAGLEV_HOME/bin/spec #{spec} } }
  end
end

desc "run the cucumber test case with mri"
task :cucumber do
  puts "\n=== NOTE: There should be nice pretty output...\n"
  sh %{ $MAGLEV_HOME/bin/cucumber features/greeter_says_hello.feature }
end

namespace :mri do
  desc "run the rspec test case with mri"
  task :rspec do
    sh %{ /opt/ruby/ruby/bin/spec -rubygems bowling_spec.rb }
  end


  desc "run the cucumber test case with mri"
  task :cucumber do
    sh %{ cucumber features/greeter_says_hello.feature }
  end
end

