task :default => :commit

#MAGLEV_CMD = "MAGLEV_OPTS= maglev-ruby -MnoRlwrap"
MAGLEV_CMD = "MAGLEV_OPTS= maglev-ruby"

ENV['MAGLEV_OPTS'] = '-MnoRlwrap -Ilib'   # Get rid of -d etc.

# desc "Commit the MDB Server code to the repository."
# task :commit, :force do |t,args|
#   sh %{ maglev-ruby commit_code.rb #{args.force} }
# end
desc "Commit the MDB Server code to the repository."
task :commit do
  sh %{ maglev-ruby commit_code.rb }
end

desc "Run tets: requires rubygems installed and a patched minitest gem"
task :test => :commit do
  Dir.glob("test/*_tests.rb") do |t|
    puts "Test: #{t}"
    sh %{ maglev-ruby -Itest #{t} }
  end
end

# These tasks control the RESTful mdb_server.rb Sinatra app
namespace :mdb do
  desc "Start the mdb_server app"
  task :start do
    sh %{ $MAGLEV_HOME/bin/rackup server.ru }
  end

  desc "List the databases in the server"
  task :list do
    sh %{ maglev-ruby -e 'p MDB::Server.db_names' }
  end

end

