task :default => :commit

ENV['MAGLEV_OPTS'] = '-Ilib'

desc "Commit the MDB Server code to the repository."
task :commit do
  sh 'maglev-ruby  commit_code.rb'
end

desc "Run test: requires the minitest gem"
task :test => [:'test:mdb', :'test:persistence', :'test:server']  # :'test:json',

namespace :test do
  desc "Run the migration tests"
  task :migration do
    sh "maglev-ruby -Ilib test/migration/migration_tests.rb"
  end

  desc "Run the persistence tests."
  task :persistence => :commit do
    sh 'ruby test/test_persistence.rb'
  end

  desc "Run the MDB::* tests."
  task :mdb => [:commit, :mdb_fixtures] do
    ['server_tests.rb', 'database_tests.rb'].each do |test|
      sh "maglev-ruby -Itest test/#{test}"
    end
  end

  desc "Load fixtures for MDB::* tests"
  task :mdb_fixtures do
    sh "maglev-ruby test/mdb_fixtures.rb"
  end

  desc "Load fixtures for mdb_server tests"
  task :mdb_server_fixtures do
    sh "maglev-ruby test/mdb_server_fixtures.rb"
  end

  # Test for the (new) Marshal based server

  desc "Test the Marshal server"
  task :server => :'test:server:server'
  namespace :server do
    task :server => [:commit, :mdb_server_fixtures] do
      sh 'maglev-ruby -Itest test/mdb_server_tests.rb'
    end
  end
end


# These tasks control the RESTful mdb_server.rb Sinatra app
namespace :server do
  desc "Start the mdb_server app"
  task :start => :commit do
    sh %{ MAGLEV_OPTS='-d' $MAGLEV_HOME/bin/rackup --port 4567 --server webrick config.ru }
  end

  desc "List the databases in the server"
  task :list do
    sh "maglev-ruby -e 'p MDB::Server.server.db_names'"
  end

  desc "Print out debug info on the server"
  task :debug do
    sh "maglev-ruby -e 'puts MDB::Server.server.debug_info'"
  end
end
