# file parser.rb
#   used for loading parser separately from bootstrap
require 'kernel/parser/RpStClasses.rb'
require 'kernel/parser/RubyNode.rb'
require 'kernel/parser/ffi.rb'
require 'kernel/parser/rp_classes.rb'
require 'kernel/parser/strscan.rb'
require 'kernel/parser/strscan2.rb'
# require 'kernel/parser/sexp.rb'
require 'kernel/parser/racc_def_parser.rb'
require 'kernel/parser/extras.rb'
require 'kernel/parser/lexer.rb'
require 'kernel/parser/ruby_parser.rb'
require 'kernel/parser/racc_init_parser.rb'
require 'kernel/parser/racc_parser.rb'
