#! /bin/csh
#
#  requires that /usr/local/bin/racc  exist
#   from installation of the Ruby  gem  racc 1.4.6  .

if ( $1 == "-D" ) then
  setenv M4FLAGS "-DPARSER_DEBUG"
else
  setenv M4FLAGS " "
endif
echo "M4FLAGS = $M4FLAGS"

rm -f parser.racc_out ruby_parser.rb racc_parser.rb lexer.rb racc.log

echo "M4FLAGS = $M4FLAGS" > racc.log

/usr/local/bin/racc -v -t -l -o parser.racc_out ruby_parser.y
if ( $status != 0) then
  echo "Error: NON-ZERO status from racc" >> racc.log
  cat racc.log
  exit 1
endif
 cat parser.racc_out | \
   sed -e '1,$s+Racc::+MagRp::+' | \
   sed -e '1,$s+require+# require+' | \
   sed -e '1,$s+racc_reduce_n+Parser::Racc_reduce_n+' | \
   sed -e '1,$s+racc_shift_n+Parser::Racc_shift_n+' | \
   sed -e '1,$s+racc_nt_base+Parser::Racc_nt_base+' | \
   sed -e '1,$s+racc_use_result_var+Racc_use_result_var+' | \
   sed -e '1,$s+, _values, result)+, vofs)+' > ruby_parser.rb
if ( $status != 0) then
  echo "Error: NON-ZERO status from sed " >> racc.log
  cat racc.log
  exit 1
endif
chmod -w ruby_parser.rb parser.racc_out 

if ( -f /usr/ccs/bin/m4 ) then
  setenv M4 /usr/ccs/bin/m4 # Solaris
else
  setenv M4 /usr/bin/m4  # Linux, Mac, others
endif

echo "# file racc_parser.rb " > racc_parser.rb
echo "#  generated by m4 processing of racc_parser.rbm4 " >> racc_parser.rb
echo "#  DO NOT EDIT THIS FILE , edit the .rbm4 files  " >> racc_parser.rb

$M4 $M4FLAGS racc_parser.rbm4 >> racc_parser.rb
if ( $status != 0) then
  echo "Error: NON-ZERO status from m4 racc_parser.rbm4 " >> racc.log
  cat racc.log
  exit 1
endif

echo "# file lexer.rb " > lexer.rb
echo "#  generated by m4 processing of lexer.rbm4 " >> lexer.rb
echo "#  DO NOT EDIT THIS FILE , edit the .rbm4 files  " >> lexer.rb

$M4 $M4FLAGS lexer.rbm4 >> lexer.rb
if ( $status != 0) then
  echo "Error: NON-ZERO status from m4 lexer.rbm4 " >> racc.log
  cat racc.log
  exit 1
endif

chmod -w racc_parser.rb lexer.rb 
