require 'rake/clean'

CLEAN.include('*~', 'a.out', 'c/*o', 'gem_*_code.log')
CLOBBER.include('c/libpsych.*')

YAML_DIR = "#{ENV['HOME']}/external/yaml-0.1.3"
FFI_DIR  = "#{ENV['HOME']}/external/ffi"

I_DIR = "#{YAML_DIR}/include"
L_DIR = "#{YAML_DIR}/src/.libs"
X_DIR = "#{ENV['HOME']}/GemStone/checkouts/git/src/experimental/yaml/c"
SH_L_VALUE = "#{L_DIR}:#{X_DIR}"

UNAME = `uname`.chomp
case UNAME
when "Linux"
  CFLAGS   = "-m64 -Wall -g -I#{I_DIR} -fPIC"
  DL_EXT   = 'so'
  L_PATH_NAME = "LD_LIBRARY_PATH"
  SH_L_PATH = "LD_LIBRARY_PATH=#{SH_L_VALUE}"
when "Darwin"
  CFLAGS  = "-m64 -Wall -g -I#{I_DIR}"
  DL_EXT   = 'dylib'
  L_PATH_NAME = "DYLD_LIBRARY_PATH"
  SH_L_PATH = "DYLD_LIBRARY_PATH=#{SH_L_VALUE}"
else
  raise "Rakefile doesn't support #{`uname`}"
end

LIBPSYCH = "c/libpsych.#{DL_EXT}"
LFLAGS  = "-Wall -m64 -L#{L_DIR} -lyaml"

task :default => :run

desc "Create #{LIBPSYCH} dynamic libraray"
task :libpsych => ["parser:#{LIBPSYCH}"]

rule '.o' => ['.c'] do |t|
  cd( File.dirname(t.source) ) do
    sh "gcc #{CFLAGS} -c -o #{File.basename t.name} #{File.basename t.source}"
  end
end

desc "Run the t.rb file"
task :run => ['lib/libpsych.rb', "parser:#{LIBPSYCH}"] do
  sh "export #{SH_L_PATH} ; maglev-ruby -d -Ilib main.rb"
end

task :env do
  ENV[L_PATH_NAME]=SH_L_VALUE
end
namespace :parser do
  task "#{LIBPSYCH}" => ['c/parser.o'] do
    opts = "-L#{L_DIR} -lyaml"

    case UNAME
    when "Linux"
      sh "gcc -shared #{opts} -m64 -Wl,-soname -Wl,#{File.basename LIBPSYCH} -o #{LIBPSYCH} c/parser.o"
    when "Darwin"
      sh "gcc -m64 -dynamiclib #{opts} -o #{LIBPSYCH} c/parser.o"
    else
      raise "Rakefile doesn't support #{`uname`}"
    end
  end

  desc "Compile files with lots of warnings"
  task :lint do
    rm_f 'c/parser.o'
    puts "LINT:  gcc #{CFLAGS} -Wall -O2 -c -o c/parser.o c/parser.c"
    sh "gcc #{CFLAGS} -Wall -O2 -c -o c/parser.o c/parser.c"
  end
end

namespace :test do
  desc "Test the emitter code from ruby"
  task :emitter do
    sh "export #{SH_L_PATH} ; maglev-ruby -Ilib test_emitter.rb"
  end

  desc "Test YAML through the Psych front door"
  task :psych => [:libpsych, :env] do
    sh 'echo DYLD_LIBRARY_PATH is: $DYLD_LIBRARY_PATH'
    sh "maglev-ruby -Ilib test_parser.rb"
  end
  desc "Test the parser code from rubyXXX"
  task :parserx do
    sh "export #{SH_L_PATH} ; maglev-ruby -Ilib test_parser.rb"
  end
end

desc "Run a ruby file using libpsych.dylib"
task :runrb, :rbfile do |task, args|
  sh "export #{SH_L_PATH} ; maglev-ruby -Ilib #{args.rbfile}"
end
