require 'rake/clean'

CLEAN.include('*~', 'gem_*_code.log')

LIB_DIR = "#{ENV['HOME']}/GemStone/checkouts/gss64bit_3.0/slow/yaml/install42/lib"

UNAME = `uname`.chomp
case UNAME
when "Linux"
  DL_EXT   = 'so'
  L_PATH_NAME = "LD_LIBRARY_PATH"
  SH_L_PATH = "LD_LIBRARY_PATH=#{LIB_DIR}"
when "Darwin"
  DL_EXT   = 'dylib'
  L_PATH_NAME = "DYLD_LIBRARY_PATH"
  SH_L_PATH = "DYLD_LIBRARY_PATH=#{LIB_DIR}"
else
  raise "Rakefile doesn't support #{`uname`}"
end

LIBPSYCH = "#{LIB_DIR}/libpsych.#{DL_EXT}"

task :default => :test

desc "Run the t.rb file"
task :run => ['lib/libpsych.rb'] do
  sh "export #{SH_L_PATH} ; maglev-ruby -d -Ilib main.rb"
end

task :env do
  ENV[L_PATH_NAME] = LIB_DIR
  puts "#{L_PATH_NAME}: #{ENV[L_PATH_NAME]}"
end

desc "Temporary: link the svn versions of libyaml and libpsych into $MAGLEV_HOME/gemstone/..."
task :devlinks do
  sh "ln -sf #{LIB_DIR}/libyaml-0.2.dylib #{ENV['MAGLEV_HOME']}/gemstone/lib/libyaml.dylib"
  sh "ln -sf #{LIB_DIR}/libpsych.dylib    #{ENV['MAGLEV_HOME']}/gemstone/lib/libpsych.dylib"
end

desc "Run all of the tests"
task :test => 'test:all'
namespace :test do
  task :all => [:parser, :emitter]

  desc "Test parsing YAML"
  task :parser => [:env] do
    sh "maglev-ruby -rubygems -Ilib tests/parser_tests.rb"
  end

  desc "Test emitting YAML"
  task :emitter => [:env] do
    sh "maglev-ruby -rubygems -Ilib tests/emitter_tests.rb"
  end

  desc "Test calling from Psych"
  task :psych => [:env] do
    sh "maglev-ruby -rubygems -Ilib -Itests tests/psych_tests.rb"
  end
end

desc "Run a ruby file using libpsych.dylib"
task :runrb, :rbfile do |task, args|
  sh "export #{SH_L_PATH} ; maglev-ruby -Ilib #{args.rbfile}"
end
