# This Gemfile manages gems for the Sinatra examples in this directory.  It
# does not manage gems for Sinatra applications in subdirectories.

source "http://rubygems.org"

gem "sinatra"

group :test do
  gem "minitest",  :require => "minitest/spec"
end
