
desc "Commit the base blog code to the repository."
task :commit, :force do |t,args|
  sh %{ maglev-ruby -MnoRlwrap commit_code.rb #{args.force} }
end

desc "Commit the code and run the app"
task :run => :commit do
  sh %{ $MAGLEV_HOME/bin/rackup }
end

"Run tets: requires rubygems installed and a p patched minitest gem"
task :tests => :commit do
  Dir.glob("test/*_tests.rb") do |t|
    sh %{ unset MAGLEV_OPTS ; maglev-ruby -MnoRlwrap #{t} }
  end
end
