
desc "Commit the base blog code to the repository"
task :commit do
  sh %{ maglev-ruby -MnoRlwrap commit_code.rb }
end

desc "Commit the code and run the app"
task :run => :commit do
  sh %{ maglev-ruby -MnoRlwrap blog_app.rb }
end

"Run tets: requires rubygems installed and a p patched minitest gem"
task :tests => :commit do
  Dir.glob("test/*_tests.rb") do |t|
    sh %{ unset MAGLEV_OPTS ; maglev-ruby -MnoRlwrap #{t} }
  end
end


