# Rake file for running sinatra apps and committing code to maglev.
# Default is to commit code (if necessary) and run both apps

task :default => :blog

desc "Commit the base blog code to the repository."
task :commit, :force do |t,args|
  sh %{ maglev-ruby commit_code.rb #{args.force} }
end

desc "Run the blog app, committing the blog code if necessary"
task :blog => :commit do
  sh %{ $MAGLEV_HOME/bin/rackup config.ru }
end

"Run tets: requires rubygems installed and a patched minitest gem"
task :tests => :commit do
  Dir.glob("test/*_tests.rb") do |t|
    sh %{ maglev-ruby #{t} }
  end
end

