
directory 'log'

desc "Run MagLev on the SCGI app"
task :maglev do
  sh "maglev-ruby -rubygems scgi_app.rb"
end

desc "Run MRI on the SCGI app"
task :mri do
  sh "ruby -rubygems scgi_app.rb"
end

desc "Rm the log files and start the lighttpd server"
task :server => 'log' do
  rm_f ['lighttpd.error.log', 'lighttpd.access.log']
  sh '/opt/local/sbin/lighttpd -D -f lighttpd.conf '
end
