
directory 'log'

desc "Run MagLev on the SCGI app"
task :maglev do
  sh "#{ENV['MAGLEV_HOME']}/bin/rackup scgi.ru"
end

desc "Run MRI on the SCGI app"
task :mri do
  sh "rackup scgi.ru"
end

desc "Rm the log files and start the lighttpd server"
task :server => 'log' do
  rm_f ['log/error.log', 'log/access.log']
  sh '/opt/local/sbin/lighttpd -D -f lighttpd.conf '
end

desc "Run Apache Bench against the server + maglev and profile output."
task :abprof do
  sh 'curl http://localhost:3000/start'
  # ab options:
  #     -k   use keep alive
  #     -c   concurrency level
  #     -t   time limit (max number of seconds)
  sh 'ab -c 1 -t 10 http://127.0.0.1:3000/foo.scgi'
#  sh 'ab -kc 10 -t 40 http://127.0.0.1:3000/foo.scgi'
  sh 'curl http://localhost:3000/stop'
  sh 'curl http://localhost:3000/report'
end

desc "Run Apache Bench against the server"
task :ab do
  # ab options:
  #     -k   use keep alive
  #     -c   concurrency level
  #     -t   time limit (max number of seconds)
  sh 'ab -c 1 -t 10 http://127.0.0.1:3000/foo.scgi'
end
