# This Gemfile manages gems for the Sinatra examples in this directory.  It
# does not manage gems for Sinatra applications in subdirectories.

source "http://rubygems.org"

gem "sinatra"

group :test do
  gem "rack-test", :require => "rack/test"
  gem "minitest",  :require => "minitest/unit"
end
