task :default => :hello

desc 'Run sinatra_hello.rb'
task :hello do
  sh 'maglev-ruby sinatra_hello.rb'
end

desc 'Run sinatra_app.rb'
task :app do
  sh 'maglev-ruby sinatra_app.rb'
end

desc 'Run the minitest for sinatra_app.rb.'
task :test do
  sh 'maglev-ruby -rubygems sinatra_app_test.rb'
end

namespace :xperimental do
  desc <<EOS
EXPERIMENTAL: Commit Sinatra framework to MagLev. This is experimental.
Read commit_sinatra.rb for details.
EOS
  task :commit do
    sh 'maglev-ruby commit_sinatra.rb'
  end
end
