
task :default => :app

desc 'Run sinatra_app.rb'
task :app do
  sh 'maglev-ruby sinatra_app.rb'
end

desc 'Run the minitest for sinatra_app.rb.'
task :test do
  sh 'maglev-ruby -rubygems sinatra_app_test.rb'
end

