
task :default => :demo

desc "Demo of using unordered collections with indexes."
task :demo do
  sh %{ maglev-ruby -Ilib index_example.rb }
end

desc "Run the tests"
task :test do
  sh %{ $MAGLEV_HOME/bin/testrb -Ilib #{FileList['test/*_test.rb']} }
end

