# Gemfile that lists gems we want to ensure install cleanly on MagLev
#
# This gemfile does not list particular versions, and the test removes any
# Gemfile.lock, so it will test that the latest versions of the gems
# install.
require 'resolv'
begin
  mirror = 'http://w2-stdev-ub10-01.gemstone.com:9292'
  Resolv.getaddress mirror
  source mirror
rescue Exception
end
source "http://rubygems.org"

gem "sinatra"
gem "rack"
gem "rack-test", :require => "rack/test"
gem "minitest",  :require => "minitest/unit"
gem "rdiscount"
gem "activemodel", "~>3.1"
gem "nokogiri"
gem "json"
gem "bcrypt-ruby"
