# Gemfile that lists gems we want to ensure install cleanly on MagLev
#
# This gemfile does not list particular versions, and the test removes any
# Gemfile.lock, so it will test that the latest versions of the gems
# install.

source "http://rubygems.org"

gem "sinatra"
gem "rack"
gem "rack-test", :require => "rack/test"
gem "minitest",  :require => "minitest/unit"
gem "rdiscount"
