task :default => :test

desc "Run a perf test"
task :run do
  sh %{ maglev-ruby -Ilib bin/script.rb }  
end

desc "Test the vsd code"
task :test, :file do |t,args|
  test_files = args.file || FileList['test/*_test.rb']
  sh %{ $MAGLEV_HOME/bin/testrb -Ilib #{test_files} }
end

desc "Commit the tree of random people"
task :commit do
  cd('../../../examples/persistence/indexing') do
    sh %{ rake commit }
  end
end

desc "commit index test data"
task :commitidx do
  sh %{ maglev-ruby -Ilib bin/data.rb }
end

desc "Run a test of the indexing performance"
task :testidx do
  sh %{ maglev-ruby -Ilib bin/test_index.rb }
end
