
task :default => :test
RAILS_INCLUDES = %w(actionmailer
                    actionpack
                    activemodel
                    activerecord
                    activeresource
                    activesupport
                    railties).inject("") { |s,p| s << " -I../rails/#{p}/lib" ; s }

MH = ENV['MAGLEV_HOME']
RAILS_INCLUDES << " -I#{MH}/lib/maglev/gems/1.8.7/gems/tzinfo-0.3.19/lib"

desc "Run the tests: takes optional file arg: 'rake test[test/foo_test.rb]'"
task :test, :file do |t, args|
  cd('test') do
    test_files = args.file || FileList['*_test.rb']
    sh %{ $MAGLEV_HOME/bin/testrb #{RAILS_INCLUDES} -I. #{test_files} }
  end
end

desc "Run the std app my_app with maglev"
task :app do
  cd('my_app') do
    sh %{ maglev-ruby -MallIvsDynamic #{RAILS_INCLUDES} -r tzinfo -r ../core_ext.rb script/rails server }
  end
end

namespace :mri do
  desc "Run the tests using MRI: takes optional file arg: 'rake test[test/foo_test.rb]'"
  task :tests, :file do |t,args|
    test_files = args.file || FileList['test/*_test.rb']
    sh %{ testrb #{RAILS_INCLUDES} -Itest #{test_files} }
  end

  desc "Run the app using MRI"
  task :app do
    cd('my_app') do
      sh %{ ruby script/rails server }
    end
  end
end
