
task :default => :test

desc "Run the tests: takes optional file arg: 'rake test[test/foo_test.rb]'"
task :test, :file do |t, args|
  test_files = args.file || FileList['test/*_test.rb']
  sh %{
    $MAGLEV_HOME/bin/testrb \
      -Irails/activesupport/lib \
      -Irails/activemodel/lib \
      -Itest \
      #{test_files}
  }
end

desc "Run the std app my_app with maglev"
task :app do
  cd('my_app') do
    sh %{ maglev-ruby \
            -I../rails/activesupport/lib \
            -I../rails/activemodel/lib \
            script/rails server
    }
  end
end

desc "Run the tests using MRI: takes optional file arg: 'rake test[test/foo_test.rb]'"
task :mri, :file do |t,args|
  test_files = args.file || FileList['test/*_test.rb']
  sh %{
    testrb \
      -Irails/activesupport/lib \
      -Irails/activemodel/lib \
      -Itest \
      #{test_files}
  }
end
