task :default => :'test:migration'

namespace :test do
  desc "Test the migrations code"
  task :migration do
    sh "maglev-ruby -Ilib test/migration_tests.rb"
# puts "========== WARNING: Running with ruby: change to maglev-ruby ====="
#    sh "ruby -Ilib test/migration_tests.rb"
  end
end
