source 'http://rubygems.org'

# gem 'rails', :path => '/Users/pmclain/GemStone/checkouts/git/examples/rails/rails'
gem 'rails', :path => "#{ENV['MAGLEV_HOME']}/examples/rails/rails"
gem 'arel',  :git => 'git://github.com/rails/arel.git'

# gem 'sqlite3-ruby', :require => 'sqlite3'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'bj'
# gem 'nokogiri', '1.4.1'
# gem 'sqlite3-ruby', :require => 'sqlite3'
# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for certain environments:
# gem 'rspec', :group => :test
# group :test do
#   gem 'webrat'
# end
